### PR TITLE
Tweaks..Tweaks...Tweaks...

### PR DESCRIPTION
**Pull request by athul**

### CODE REVIEW

**Comment by athul** [comment]
@haxzie and @akzhy should we push this to deployment?

**Comment by athul** [comment]
@akzhy and @haxzie any ideas on how to normalize the logo for the sponsor section? I suck at CSS :smiling_imp:

**Review by haxzie-xx — APPROVED** [review]

**Comment by haxzie-xx** [comment]
Looks good to me :+1:

**Comment by athul** [comment]
> Looks good to me

but don't you think that sponsor logos should all be at a consistent ratio?

**Comment by athul** [comment]
Should we mege this?

**Pull request merged**
