### PR TITLE
updated bits...

### PR DESCRIPTION
**Pull request by athul**
updated with bits.... ill update the gh-pages of this branch too

### CODE REVIEW

**Comment by athul** [comment]
https://mehac1.netlify.com/

Currently deployed to this...

**Review by haxzie-xx — CHANGES_REQUESTED** [review]
The file size of the new images, especially `img/back1.jpg` and `img/back2.jpg` is too high for a simple website. Consider cutting the size down, this will help in faster loading speeds in mobile devices and desktop devices alike.

**Comment by athul** [comment]
> The file size of the new images, especially `img/back1.jpg` and `img/back2.jpg` is too high for a simple website. Consider cutting the size down, this will help in faster loading speeds in mobile devices and desktop devices alike.

I was thinking that if we merge it and use the img bot.... We could resolve that

**Comment by haxzie-xx** [comment]
The maximum optimization I got by img bot is 20%, don't rely on it because the resolution of the images are too high.

**Comment by athul** [comment]
> The maximum optimization I got by img bot is 20%, don't rely on it because the resolution of the images are too high.

Okay, I'll send it via WhatsApp or via directly link it...
Which do you prefer?

**Comment by haxzie-xx** [comment]
If you have photoshop with you, you can do it yourself. Just reduce the resolution of the image.

**Comment by athul** [comment]
https://5c9a40912ed76d0008f478f5--mehac1.netlify.com/ 

published the branch

**Review by haxzie-xx — APPROVED** [review]
Much better :+1:  Merge it when you are ready.

**Comment by athul** [comment]
okay... @haxzie Merge it....

**Pull request merged**
