### PR TITLE
New Hover for span

### PR DESCRIPTION
**Pull request by athul**
@akzhy Bro Let us test a case when the Image is hovered, the span also hovers. We can do that in Js right.

### CODE REVIEW

**Comment by akzhy** [comment]
Which part of the website are you talking about @Athul-CA

**Comment by athul** [comment]
The `<span>` element in the sponsors section for what tyoe of thing they are sponsoring

**Comment by akzhy** [comment]
Done, no need for js @Athul-CA

**Review by athul — COMMENTED** [review]
Poliye.... You are on Fire mate

**Pull request merged**
